# Generated by Django 2.2.13 on 2020-06-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hjhjh'),
    ]

    operations = [
        migrations.CreateModel(
            name='JHgjhg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hgfkhgck', models.BigIntegerField()),
            ],
        ),
    ]
